language: generic

before_script:
  - npm install -g esy
  - esy install

script:
  - BISECT_ENABLE=yes esy dune build ./tester.exe
  - esy dune exec ./tester.exe
  - esy dune exec bisect-ppx-report -- html
  - cat _coverage/index.html
  - esy dune exec bisect-ppx-report -- summary

notifications:
  email:
    on_success: always
    on_failure: always
