language: generic
dist: bionic

before_script:
  - npm install -g esy
  - esy install

script:
  - esy dune runtest --instrument-with bisect_ppx --force
  - esy bisect-ppx-report html
  - cat _coverage/index.html
  - esy bisect-ppx-report summary
